insert into user (fullname, password, email) values ('admin', '$2a$12$Ass3YFsOBQ.36vmAqUsGPucTiSQC35mKqiYb2ibg3yHHLxj.rJP2q', 'admin@techmaster.vn');
insert into user (fullname, password, email) values ('John Stone', '123', 'john@st.mail');
insert into user (fullname, password, email) values ('Fred Guy', '456', 'fred@to.com');
insert into user (fullname, password, email) values ('Quang Minh', 'qmd', 'quangminh@vn.com');
insert into user (fullname, password, email) values ('Cuong Trinh', 'tmc', 'cuong@techmaster.vn');
insert into user (fullname, password, email) values ('Philip Lamn', 'phl', 'philip@de.com');
insert into user (fullname, password, email) values ('Mendy Shaw', 'mds', 'mendy@yahoo.com');
insert into user (fullname, password, email) values ('Ha Manh', 'ha2002', 'hmanh@java.com');
insert into user (fullname, password, email) values ('Thang Tran', 'abc', 'tthang@learn.com');
insert into user (fullname, password, email) values ('Nguyen Duy', 'def', 'duynguyen@hut.edu');
